# Generated by Django 6.0 on 2025-12-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Negative"),
                            (1, "Positive"),
                            (98, "Not assessed"),
                            (99, "Unknown"),
                        ]
                    ),
                ),
            ],
        ),
    ]
